export const DEMO_PROJECTS = [
  {
    id: 'demo-1',
    projectName: 'Thompson Mortgage Refinance',
    member: 'Carol Thompson',
    projectType: 'Refinance',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2026-05-30',
    waitingOn: 'Underwriter to clear income conditions',
    nextSteps: 'Respond to underwriter conditions\nPrepare closing disclosure\nSchedule closing date with title company',
  },
  {
    id: 'demo-2',
    projectName: 'Johnson Auto Loan',
    member: 'Marcus Johnson',
    projectType: 'Auto Loan',
    status: 'Blocked',
    priority: 'High',
    dueDate: '2026-05-15',
    waitingOn: 'Employer to return income verification form',
    nextSteps: 'Follow up with employer HR\nRe-run credit if verification delayed past June 1',
  },
  {
    id: 'demo-3',
    projectName: 'Williams Home Equity Line',
    member: 'Patricia Williams',
    projectType: 'Home Equity',
    status: 'In Progress',
    priority: 'Medium',
    dueDate: '2026-06-15',
    waitingOn: '',
    nextSteps: 'Order title search\nSchedule property inspection\nSend member rate lock options',
  },
  {
    id: 'demo-4',
    projectName: 'Garcia Business Expansion Loan',
    member: 'Elena Garcia',
    projectType: 'Business Loan',
    status: 'Blocked',
    priority: 'High',
    dueDate: '2026-05-20',
    waitingOn: 'Accountant to submit last 2 years of business financials',
    nextSteps: 'Contact accountant — third follow-up\nReview business plan once financials arrive',
  },
  {
    id: 'demo-5',
    projectName: 'Anderson Mortgage Purchase',
    member: 'David Anderson',
    projectType: 'Mortgage',
    status: 'In Progress',
    priority: 'Medium',
    dueDate: '2026-06-30',
    waitingOn: '',
    nextSteps: 'Confirm purchase agreement is fully executed\nOrder appraisal\nSend initial disclosure package',
  },
  {
    id: 'demo-6',
    projectName: 'Rivera Personal Loan',
    member: 'Sofia Rivera',
    projectType: 'Personal Loan',
    status: 'Not Started',
    priority: 'Low',
    dueDate: '2026-07-10',
    waitingOn: '',
    nextSteps: 'Pull credit report\nVerify debt-to-income ratio',
  },
  {
    id: 'demo-7',
    projectName: 'Patel Auto Loan',
    member: 'Amir Patel',
    projectType: 'Auto Loan',
    status: 'Not Started',
    priority: 'Medium',
    dueDate: '2026-06-05',
    waitingOn: '',
    nextSteps: 'Verify proof of insurance\nConfirm trade-in vehicle value\nRun credit application',
  },
  {
    id: 'demo-8',
    projectName: 'Chen Account Opening',
    member: 'Linda Chen',
    projectType: 'Account Opening',
    status: 'Complete',
    priority: '',
    dueDate: '2026-05-22',
    waitingOn: '',
    nextSteps: '',
  },
]
